### ISSUE TITLE
SMS Code Autofill in iOS Apps

### ISSUE THREAD

**Issue by MooseQuest** [SquadQuest/SquadQuest#106]
When receiving codes in iOS they are not populating from the message. This feature enables the user:

- Less mistakes when entering codes
- Maintain feature parody in iOS

<img width="1029" alt="Screenshot 2024-07-08 at 15 39 46" src="https://github.com/SquadQuest/SquadQuest/assets/20930225/111e923f-b6ae-4ed2-855e-72fe6552801b">

**Comment by themightychris** [comment]
I don't have any SIM for my test iOS device so this isn't something I've been able to play with. According to the description of the Flutter ['sms_autofill'](https://pub.dev/packages/sms_autofill) package:

> For iOS, this package is not needed as the SMS autofill is provided by default, but not for Android, that's where this package is useful.

So there must just be some annotation missing for linking the OTP field to incoming OTP SMS messages. That plugin comes with field widgets though so maybe just switching to that will make it work. I'm not able to test it though—maybe a good first issue for a contributor on iPhone :-)

**Comment by themightychris** [comment]
Looks like it can't be done right now on Android with Twilio Verify: https://github.com/supabase/auth/issues/1235

And it sounds like there's no setup to be done for helping make it work on iOS—iOS should pop up the code as pasteable by the user if it automagically detects that that's a good idea. I feel like I've seen it happen on people's screens before with SquadQuest. Maybe the way the current OTP text field is set up doesn't make it work consistently though and using a more dedicated 6-digit pin field like the one `sms_autofill` comes with would help iOS know to do it

**Comment by themightychris** [comment]
@MooseQuest see if this is improved by 71f2abf3bf2f43b2617454845a2a4ae9c6dace57—you'll have to wait for v1.9.1 to hit the app store later today

**Comment by themightychris** [comment]
This can't work on Android right now because Twilio Verify only lets you select from a small set of preexisting templates for the verification text messages—and for some reason none of them match the format Android requires

**Comment by chrisly** [comment]
Verified that it works on iOS 17.6.1

**Comment by themightychris** [comment]
Awesome, closing
