### ISSUE TITLE
Detect when phone numbers pasted with country code

### ISSUE THREAD

**Issue by themightychris** [SquadQuest/SquadQuest#147]
When you copy a phone number from your contacts, it may already include a country code

Currently, if you paste that into a phone field, you then have to manually delete it. The UX for doing so is really bad with the auto formatting 

Numbers pasted with country code should be detected and have the country code automatically extracted and set up the county code drop-down

**Comment by IguJl15** [comment]
Understand. I already know how to implement this. We will see the feature in action until next Friday, ok?
